on: [push]

jobs:
  gitversion_job:
    runs-on: ubuntu-latest
    name: A job to run GitVersion
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.301
      - name: Install tools
        run: dotnet tool restore
      - id: foo
        uses: wekempf/GitVersion.Tool-action@v3
      - run: echo semver ${{ steps.foo.outputs.semver }}
        shell: bash